
[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "Light"

[font.bold_italic]
family = "Fira Code"
style = "Light Italic"

[font.italic]
family = "Fira Code"
style = "Extra Light Italic"

[font.normal]
family = "Fira Code"
style = "ExtraLight"

[window]
decorations = "none"
opacity = 0.7
dynamic_padding = true

[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]
